#!/bin/bash

sudo rm -rf /Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/File\ Templates/Karakuri\ Game/
sudo rm -rf /Library/Application Support/Apple/Developer Tools/File\ Templates/Karakuri\ Game/
sudo rm -rf /Library/Application Support/Developer/2.5/Xcode/File\ Templates/Karakuri\ Game/
sudo rm -rf /Developer/Library/Xcode/File\ Templates/Karakuri\ Game/

sudo rm -rf /Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/Project\ Templates/Karakuri\ Game/
sudo rm -rf /Library/Application Support/Apple/Developer Tools/Project\ Templates/Karakuri\ Game/
sudo rm -rf /Library/Application Support/Developer/2.5/Xcode/Project\ Templates/Karakuri\ Game/
sudo rm -rf /Developer/Library/Xcode/Project\ Templates/Karakuri\ Game/
